config/routes.rb
Twit1::Application.routes.draw do
  get "pages/home"
  get "pages/love"
  
  post "pages/home", :as => "search"
  post "pages/love", :as => "feeling_search"
  
  root :to => "pages#home"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
require "net/http"

class PagesController < ApplicationController
  
  def home
    search_str = params[:search_str]
    if search_str.present?
      query = search_str.gsub(/\s/, '+')
      raw_data = Net::HTTP.get(URI.parse("http://search.twitter.com/search.json?q=#{query}&rpp=100"))
      @data = JSON.parse(raw_data)
    end
  end
  
  def love
    search_str = params[:feeling_str]
    if search_str.present?
      query = search_str.gsub(/\s/, '+')
      @love_str = "+I+love+#{query}"
      @hate_str = "+I+hate+#{query}"
      
      #@love_str << 
      love_raw_data = Net::HTTP.get(URI.parse("http://search.twitter.com/search.json?q=#{@love_str}&rpp=100"))
      @love_data = JSON.parse(love_raw_data)
      hate_raw_data = Net::HTTP.get(URI.parse("http://search.twitter.com/search.json?q=#{@hate_str}&rpp=100"))
      @hate_data = JSON.parse(hate_raw_data)
    end 
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twit1</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  
<%= yield %>

</div>
</body>
</html>

app/views/pages/home.html.erb
<h1>Twitter Search</h1>

<%= form_tag(search_url) do %>
  <%=text_field_tag :search_str%> | <%=submit_tag "Find Tweets!"%>
<% end %>
<p></p>
<% if @data.present? %>
<h2><%=@data["query"]%></h2>
  <% @data["results"].each  do |tweet| %>
    <li><%= tweet["from_user"] %> tweeted "<%= tweet["text"]%>"</li>
  <% end %>
<% end %>

app/views/pages/love.html.erb
<%=form_tag feeling_search_url do |feeling_str| %>
 <%=text_field_tag :feeling_str %> | <%=submit_tag "Feel It!"%>
<% end %>

<div id="love">
<% if @love_data.present? %>
<h2><%=@love_data["query"]%></h2>
  <% @love_data["results"].each  do |tweet| %>
    <li><%= tweet["from_user"] %> tweeted "<%= tweet["text"]%>"</li>
  <% end %>
<% end %>
</div>

<div id="hate">
<% if @hate_data.present? %>
<h2><%=@hate_data["query"]%></h2>
  <% @hate_data["results"].each  do |tweet| %>
    <li><%= tweet["from_user"] %> tweeted "<%= tweet["text"]%>"</li>
  <% end %>
<% end %>
</div>